version: '3'

services:
  apache:
    image: httpd:latest
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs/
    restart: always
    platform: linux/arm64/v8