services:
  kafka_test:
    container_name: kafka_test
    depends_on:
    - kafka_test_zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_test:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_BROKER_ID: '1'
      KAFKA_DEFAULT_REPLICATION_FACTOR: '1'
      KAFKA_HEAP_OPTS: -Xmx1g -Xms1g
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_NUM_PARTITIONS: '3'
      KAFKA_ZOOKEEPER_CONNECT: kafka_test_zookeeper:2181
    image: confluentinc/cp-kafka:2.8
    ports:
    - 9092:9092
    restart: always
    volumes:
    - kafka_test_data:/var/lib/kafka/data
  kafka_test_zookeeper:
    container_name: kafka_test_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: '2181'
      ZOOKEEPER_TICK_TIME: '2000'
    image: zookeeper:latest
    ports:
    - 2181:2181
    restart: always
version: '3'
volumes:
  kafka_test_data:
    driver: local
