services:
  kafka_212:
    container_name: kafka_212
    depends_on:
    - kafka_212_zookeeper
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_NODE_ID: '1'
      KAFKA_CFG_NUM_PARTITIONS: '3'
      KAFKA_CFG_ZOOKEEPER_CONNECT: kafka_212_zookeeper:2181
      KAFKA_HEAP_OPTS: -Xmx1g -Xms1g
    image: bitnami/kafka:6.2.13
    ports:
    - 9092:9092
    - 9093:9093
    restart: always
    volumes:
    - kafka_212_data:/bitnami/kafka
  kafka_212_zookeeper:
    container_name: kafka_212_zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
    image: bitnami/zookeeper:latest
    ports:
    - 2181:2181
    restart: always
    volumes:
    - kafka_212_zookeeper_data:/bitnami/zookeeper
version: '3'
volumes:
  kafka_212_data:
    driver: local
  kafka_212_zookeeper_data:
    driver: local
